Adding new sample scripts which leverage Apps and Management SDKs
cohesity/app-sdk-python pull request #1
Opened 2019-04-11 11:31 UTC by hemanshu-cohesity

These are updated Cohesity Management SDK scripts, which leverages authentication using Cohesity Apps APIs. EasyScript App will have a reference to this samples folder in the App.

2019-04-11 16:18 UTC, pyashish requested changes
LGTM most of the part, Please fix the comments. 
Also, just my 2c : I don't see how the samples are related to App SDK. Why would anyone just list from App sdk

2019-04-11 16:18 UTC, ashish-cohesity commented on cohesity_app_sdk/samples/clone_and_update_view/clone_and_update_view.py
> +def get_mgnt_token():
typo: get_mgmt_token()

2019-04-11 16:18 UTC, ashish-cohesity commented on cohesity_app_sdk/samples/clone_and_update_view/clone_and_update_view.py
> +                                        auth_token=mgmt_auth_token)
correct Intend

2019-04-11 16:18 UTC, ashish-cohesity commented on cohesity_app_sdk/samples/clone_and_update_view/clone_and_update_view.py
> +    To get the management access token from athena to authenticate
Change Athena to App Server.

2019-04-11 16:18 UTC, ashish-cohesity commented on cohesity_app_sdk/samples/clone_and_update_view/clone_and_update_view.py
> +                                          " to s3 only.")
Isn't this KNFSONLY ?

2019-04-11 16:18 UTC, ashish-cohesity commented on cohesity_app_sdk/samples/list_protection_jobs/list_protection_jobs.py
> +def get_mgnt_token():
typo

2019-04-11 16:18 UTC, ashish-cohesity commented on cohesity_app_sdk/samples/list_protection_jobs/list_protection_jobs.py
> +                                      auth_token=mgmt_auth_token)
correct intend

2019-04-11 16:18 UTC, ashish-cohesity commented on cohesity_app_sdk/samples/list_unresolved_alerts/list_unresolved_alerts.py
> +                                         auth_token=mgmt_auth_token)
intend

2019-04-11 16:18 UTC, ashish-cohesity commented on cohesity_app_sdk/samples/on_demand_job_run/on_demand_job_run.py
> +def get_mgnt_token():
typo

2019-04-11 16:18 UTC, ashish-cohesity commented on cohesity_app_sdk/samples/on_demand_job_run/on_demand_job_run.py
> +    mgmt_auth_token = get_mgnt_token()
typo

2019-04-11 16:18 UTC, ashish-cohesity commented on cohesity_app_sdk/samples/on_demand_job_run/on_demand_job_run.py
> +                                         auth_token=mgmt_auth_token)
Intend

2019-04-12 14:11 UTC, hemanshu-cohesity commented
As discussed, moving these samples to another repo

2019-04-12 14:11 UTC, closed without merging